package com.rabbit.gui.reference;

import java.util.Arrays;

import net.minecraftforge.fml.common.ModMetadata;

public class MetaData {
	public static ModMetadata init(ModMetadata metadata) {
		metadata.modId = Reference.MOD_ID;
		metadata.name = Reference.MOD_NAME;
		metadata.description = "Graphical framework built on top of Forge Mod Loader and designed to facilitate the creation of graphical user interfaces";
		metadata.url = "https://github.com/FRedEnergy/rabbit-gui";
		metadata.version = Reference.VERSION;
		metadata.authorList = Arrays.asList("RedEnergy");
		metadata.credits = "";
		metadata.autogenerated = false;
		return metadata;
	}
}
